config/routes.rb
Rails.application.routes.draw do
  root "manufacturers#index"

  resources :manufacturers
  resources :cars

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :manufacturer, :color, presence: true
  validates :mileage, numericality: { only_integer: true }
  validates :year, numericality:  { greater_than_or_equal_to: 1920 }
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true, uniqueness: { message: "That Manufacturer already exists!" }
  validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to cars_path, notice: "Your record has been created successfully!"
    else
      render "new"
    end
  end

  private

  def car_params
    params.require(:car).permit(:manufacturer_id, :color, :year, :mileage, :description)
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      redirect_to manufacturers_path, notice: "Your record has been created successfully!"
    else
      flash[:notice] = "Your record could not be completed"
      render "new"
    end
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h3>cars</h3>

<%= link_to "Create a record for new a car!", new_car_path %>
<ul>
  <% @cars.each do |car| %>
    <li><%= "#{ car.manufacturer.name } - #{ car.color } - #{ car.year } - #{ car.mileage } - #{ car.description }" %></li>
  <%end%>
</ul>
<br>
<%= link_to "Click here to add a company", new_manufacturer_path%>

app/views/cars/new.html.erb
<%= form_for Car.new do |f| %>

  <% if @car.errors.any? %>
    <p><%= "#{@car.errors.count} prevented your record from being saved:" %></p>
    <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :manufacturer_id %>
  <%= f.collection_select :manufacturer_id, Manufacturer.all.order(:name), :id, :name, include_blank: true %>
  </div>

  <div>
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>

   <div>
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>

  <div>
    <%= f.label :mileage %><br>
    <%= f.text_field :mileage %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
    <% if notice %>
          <p class="notice"><%= notice %></p>
    <% end %>
  </body>
</html>

app/views/manufacturers/index.html.erb
<h3>Manufacturers</h3>

<%= link_to "Create a record for a car manufacturer!", new_manufacturer_path %>
<ul>
  <% @manufacturers.each do |manufacturer| %>
    <li><%= "#{ manufacturer.name } - #{ manufacturer.country }" %></li>
  <%end%>
</ul>
<br>
<%= link_to "Click here to add a car to a company", new_car_path %>

app/views/manufacturers/new.html.erb
<%= form_for Manufacturer.new do |f| %>

  <% if @manufacturer.errors.any? %>
    <p><%= "#{@manufacturer.errors.count} prevented your matchup from being saved:" %></p>
    <ul>
      <% @manufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>

  <%= f.submit "Submit" %>
<% end %>